# Generated by Django 5.0.2 on 2024-06-05 17:22

import django.core.validators
import django.db.models.deletion
import django_minio_backend.models
import uuid
import video_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": '"video_data"."users"',
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_publication",
                    models.DateTimeField(
                        auto_now_add=True,
                        validators=[video_app.models.check_date],
                        verbose_name="date publication",
                    ),
                ),
                ("name", models.TextField(max_length=100, verbose_name="name video")),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django_minio_backend.models.MinioBackend(
                            bucket_name="djangob"
                        ),
                        upload_to=django_minio_backend.models.iso_date_prefix,
                        validators=[
                            django.core.validators.FileExtensionValidator(("mp4",))
                        ],
                        verbose_name="video",
                    ),
                ),
                (
                    "cover_video_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=django_minio_backend.models.MinioBackend(
                            bucket_name="djangob"
                        ),
                        upload_to=django_minio_backend.models.iso_date_prefix,
                        verbose_name="cover video",
                    ),
                ),
                ("during", models.PositiveIntegerField(verbose_name="during")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="discription video",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_app.customuser",
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "video",
                "verbose_name_plural": "videos",
                "db_table": '"video_data"."videos"',
                "ordering": ["date_publication"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_publication",
                    models.DateTimeField(
                        auto_now_add=True,
                        validators=[video_app.models.check_date],
                        verbose_name="date publication",
                    ),
                ),
                ("text", models.TextField(null=True, verbose_name="text")),
                (
                    "count_likes",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="count likes"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_app.customuser",
                        verbose_name="user",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_app.video",
                        verbose_name="video",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "db_table": '"video_data"."comments"',
                "ordering": ["date_publication"],
            },
        ),
    ]
