# Generated by Django 5.0.2 on 2024-04-23 08:05

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_name",
                    models.TextField(max_length=100, verbose_name="user name"),
                ),
                (
                    "date_registrated",
                    models.DateTimeField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.datetime.now
                            )
                        ],
                        verbose_name="date registrated",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": '"video_data"."users"',
                "ordering": ["date_registrated"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_publication",
                    models.DateTimeField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.datetime.now
                            )
                        ],
                        verbose_name="date publication",
                    ),
                ),
                ("name", models.TextField(max_length=100, verbose_name="name")),
                ("during", models.PositiveIntegerField(verbose_name="during")),
            ],
            options={
                "verbose_name": "video",
                "verbose_name_plural": "videos",
                "db_table": '"video_data"."videos"',
                "ordering": ["date_publication"],
            },
        ),
        migrations.CreateModel(
            name="UserVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_app.user",
                        verbose_name="user",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_app.video",
                        verbose_name="video",
                    ),
                ),
            ],
            options={
                "verbose_name": "relationship user video",
                "verbose_name_plural": "relationships user video",
                "db_table": '"video_data"."user_video"',
                "unique_together": {("user", "video")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="videos",
            field=models.ManyToManyField(
                through="video_app.UserVideo",
                to="video_app.video",
                verbose_name="videos",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_publication",
                    models.DateTimeField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.datetime.now
                            )
                        ],
                        verbose_name="date publication",
                    ),
                ),
                ("text", models.TextField(null=True, verbose_name="text")),
                (
                    "count_likes",
                    models.PositiveIntegerField(blank=True, verbose_name="count likes"),
                ),
                (
                    "video",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_app.video",
                        verbose_name="video",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "db_table": '"video_data"."comments"',
                "ordering": ["date_publication"],
            },
        ),
    ]
