# Generated by Django 5.0.2 on 2024-04-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_text",
            field=models.TextField(verbose_name="comment text"),
        ),
    ]
