# Generated by Django 5.0.2 on 2024-04-23 08:38

import video_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_publication",
            field=models.DateTimeField(
                validators=[video_app.models.check_date],
                verbose_name="date publication",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_registrated",
            field=models.DateTimeField(
                validators=[video_app.models.check_date],
                verbose_name="date registrated",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="date_publication",
            field=models.DateTimeField(
                validators=[video_app.models.check_date],
                verbose_name="date publication",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="name",
            field=models.TextField(max_length=100, verbose_name="name video"),
        ),
    ]
