# Generated by Django 5.0.2 on 2024-04-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0002_alter_comment_date_publication_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="video"
            ),
        ),
    ]
