# Generated by Django 5.0.2 on 2024-04-22 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0002_alter_comment_comment_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment_text",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="name_video",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="video",
            name="comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="video_app.video",
                verbose_name="video",
            ),
        ),
    ]
