# Generated by Django 5.0.2 on 2024-05-04 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0004_alter_user_options_remove_user_date_registrated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="",
                validators=[django.core.validators.FileExtensionValidator(("mp4",))],
                verbose_name="video",
            ),
        ),
    ]
