name: Main test
on: [push]
jobs:
  linter_for_main:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
      - name: Flake8
        run: flake8 .

  container-job:
          name: Tests
          runs-on: ubuntu-latest
          services:
            postgres:
              image: postgres
              env:
                PG_HOST: 127.0.0.1
                PG_PORT: 5555
                PG_USER: test
                PG_PASSWORD: test
              ports:
              - 5555:5432
          steps:
          - uses: actions/checkout@v2
          - name: Python installation
            uses: actions/setup-python@v2
            with:
              python-version: 3.11