name: Main test
on: [push]
jobs:

  linter_for_main:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8 .
    
  tests:
      name: Tests Django
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres
          env:
            POSTGRES_USER: sirius
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: videos_db
          ports:
          - 38700:5432
      steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install numpy
      - name: Run tests
        env:
          PG_HOST: 127.0.0.1
          PG_PORT: 38700
          PG_USER: sirius
          PG_PASSWORD: 123
          PG_DBNAME: videos_db
        run: |
          python3 manage.py test tests

